[package]
name = "arweave-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretend = "0.3.0"
serde = { version = "1.0.144", features = ["derive"]}
serde_json = { version = "1.0.85" }
thiserror = "1.0.34"